export const DJANGO_SSO_LOGIN_URL = process.env.DJANGO_SSO_LOGIN_URL
export const DJANGO_SSO_LOGOUT_URL = process.env.DJANGO_SSO_LOGOUT_URL
export const DJANGO_SSO_PROFILE_URL = process.env.DJANGO_SSO_PROFILE_URL